level5_auth/level5_auth/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('',include("myApp.urls")),
    path('admin/', admin.site.urls),
]

level5_auth/myApp/urls.py
from django.urls import path
from myApp import views

app_name = 'myApp'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('special/', views.special, name='special'),
]

level5_auth/myApp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    portfolio = models.URLField(blank=True)
    dp = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

level5_auth/myApp/forms.py
from django import forms
from django.contrib.auth.models import User
from myApp.models import UserInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = ['portfolio', 'dp']

level5_auth/myApp/views.py
from django.shortcuts import render
from myApp.forms import UserForm, UserProfileForm
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def index(req):
    return render(req, 'myApp/index.html')


def register(req):
    registered = False
    if req.method == "POST":
        user_form = UserForm(data=req.POST)
        profile_form = UserProfileForm(data=req.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in req.FILES:
                profile.profile_pic = req.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(req, 'myApp/registration.html',
                  {'registered': registered, 'user_form': user_form, 'profile_form': profile_form})


def user_login(req):
    if req.method == "POST":
        username = req.POST.get('username')
        password = req.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(req, user)
                return HttpResponseRedirect(reverse('myApp:index'))
            else:
                return HttpResponse("Account Not Active")

        else:
            print("Login Failed for")
            print("Username:{} and Password:{}".format(username, password))
            return HttpResponse("Invalid Credentials. Try Again")

    else:
        return render(req, 'myApp/login.html', {})


@login_required
def user_logout(req):
    logout(req)
    return HttpResponseRedirect(reverse('myApp:index'))


@login_required
def special(req):
    return HttpResponse("Only Logged In Users can see this!")

level5_auth/templates/myApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'myApp:index' %}">Home</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'myApp:register' %}">Register</a></li>

            {% if user.is_authenticated %}
            <li><a href="{% url 'myApp:user_logout' %}" class="navbar-link">Logout</a></li>
            {% else %}
            <li><a href="{% url 'myApp:user_login' %}" class="navbar-link">Login</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block body_block %}
    {% endblock %}
</div>
</body>
</html>

level5_auth/templates/myApp/index.html
<!DOCTYPE html>
{% extends "myApp/base.html" %}

{% block body_block%}

<div class="jumbotron">
    <h1>Django Level 5</h1>
</div>

{% endblock %}

level5_auth/templates/myApp/login.html
<!DOCTYPE html>
{% extends "myApp/base.html" %}
{% load staticfiles %}

{% block body_block %}

<div class="jumbotron">
    <h1>Login Here</h1>
    <form action="{% url 'myApp:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">UserName:</label>
        <input type="text" placeholder="Enter Username" name="username">
        <label for="password">Password:</label>
        <input type="password" placeholder="Enter Password" name="password">

        <input type="submit" value="Login">
    </form>
</div>

{% endblock %}

level5_auth/templates/myApp/registration.html
<!DOCTYPE html>
{% extends "myApp/base.html" %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">
    {% if registered %}
    <h1>Thanks for Registering!</h1>

    {% else %}
    <h1>Register Here!</h1>
    <h2>Fill The Form Below: </h2>

    <form method="post" enctype="multipart/form-data">
        {{user_form.as_p}}
        {{profile_form.as_p}}
        <input type="submit" value="Register">
        {% csrf_token %}
    </form>
    {% endif %}
</div>

{% endblock %}