level4_templates/level4_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('myApp.urls')),
    path('admin/', admin.site.urls),
]

level4_templates/myApp/urls.py
from myApp import views
from django.urls import path

app_name = 'myApp'
urlpatterns = [
    path('', views.index, name='index'),
    path('relative/', views.relative, name='relative'),
    path('random/', views.random, name='random')
]

level4_templates/myApp/views.py
from django.shortcuts import render


# Create your views here.
def index(req):
    dict = {'text': "Hi There!", 'number': 100}
    return render(req, 'myApp/index.html', context=dict)


def relative(req):
    return render(req, 'myApp/relative_urls.html')


def random(req):
    return render(req, 'myApp/random.html')

level4_templates/templates/myApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'myApp:index' %}">Home</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'myApp:random' %}">Random</a></li>
        </ul>
    </div>
</nav>

<div class="container">
    {% block body_block%}
    #BLOCK ALL THIS CODE
    {% endblock %}
</div>
</body>
</html>

level4_templates/templates/myApp/index.html
<!DOCTYPE html>
{% extends 'myApp/base.html' %}
{% load my_custom %}
{% block body_block %}
<h1>Welcome to Index</h1>
<h2>{{text|cut_string:'Hi'}}</h2>
<h2>{{number|add:69}}</h2>
{% endblock %}

level4_templates/templates/myApp/random.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Random Page</h1>
</body>
</html>

level4_templates/templates/myApp/relative_urls.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Relative URL Templates</h1>
<a href="{% url 'myApp:index' %}">Index</a>
<a href="{% url 'myApp:random' %}">Random</a>
<a href="{% url 'admin:index' %}">Admin Page</a>
</body>
</html>